#!/usr/bin/env python3
"""Generate source/core/fedata_tables.c from FireEditor's units.xml / classes.xml.

The XML files in tools/data/ come from Danius88/fire-editor-awakening (GPLv3),
the open rewrite of Olmectron's FireEditor.

Usage:  python tools/gen_fedata.py
"""
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "data")
OUT = os.path.join(ROOT, "source", "core", "fedata_tables.c")
STATS = ["hp", "str", "mag", "skl", "spd", "lck", "def", "res"]


def stat_row(elem):
    return [int(elem.get(s, "0")) for s in STATS]


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_row(vals):
    return "{" + ", ".join("%3d" % v for v in vals) + "}"


def load(path, tag):
    rows = {}
    for e in ET.parse(path).getroot().findall(tag):  # direct children only; comments are skipped
        rows[int(e.get("id"))] = e
    ids = sorted(rows)
    if ids != list(range(len(ids))):
        raise SystemExit("%s: ids are not contiguous from 0: %r" % (path, ids))
    return [rows[i] for i in ids]


def main():
    # skills.xml lists id 100 twice; keep the first occurrence
    skills = {}
    for e in ET.parse(os.path.join(DATA, "skills.xml")).getroot().findall("skill"):
        skills.setdefault(int(e.get("id")), e)
    if sorted(skills) != list(range(len(skills))):
        raise SystemExit("skills.xml: ids are not contiguous")

    units = load(os.path.join(DATA, "units.xml"), "unit")
    classes = load(os.path.join(DATA, "classes.xml"), "class")

    out = []
    out.append("// GENERATED by tools/gen_fedata.py from tools/data/*.xml. Do not edit by hand.")
    out.append("// Data source: Danius88/fire-editor-awakening (GPLv3), after Olmectron's FireEditor.")
    out.append('#include "core/fedata.h"')
    out.append("")
    # Display names: the two Avatars are shown as the default Robins
    NAME_OVERRIDE = {"0": "(M) Robin", "1": "(F) Robin"}
    out.append("const fe_char_info fe_chars[FE_CHAR_COUNT] = {")
    for u in units:
        out.append("    { %-16s %s, %s },  // %s" % (
            c_str(NAME_OVERRIDE.get(u.get("id"), u.get("name"))) + ",",
            c_row(stat_row(u.find("additions"))),
            c_row(stat_row(u.find("modifiers"))),
            u.get("id")))
    out.append("};")
    out.append("")
    # Recruit data: gender, fixed parent (children), starting class, personal skills
    out.append("const fe_char_recruit fe_recruit[FE_CHAR_COUNT] = {")
    for u in units:
        flags = [f.text for f in u.find("flags").findall("flag")] if u.find("flags") is not None else []
        female = "0" in flags
        cls_el = u.find("fClasses" if female else "mClasses")
        start = cls_el.get("class1") if cls_el is not None else ""
        if not start:
            other = u.find("mClasses" if female else "fClasses")
            start = other.get("class1") if other is not None and other.get("class1") else "4"
        sk = u.find("skills").attrib if u.find("skills") is not None else {}
        pskills = [int(sk.get("skill%d" % i, "0") or 0) for i in range(1, 6)]
        parent = int(u.get("parent")) if u.get("parent") else -1
        if u.get("name") == "Cynthia":
            parent = 12  # units.xml lists Lon'qu (13); Cynthia's fixed parent is Sumia
        hair = (u.get("color") or "#ffffff").lstrip("#")[:6]
        custom = 1 if u.get("customColor") == "true" else 0
        out.append("    { %d, %3d, %2d, {%s}, 0x%s, %d },  // %s" % (1 if female else 0, parent, int(start),
                                                       ", ".join(str(x) for x in pskills), hair.upper(), custom,
                                                       u.get("name")))
    out.append("};")
    out.append("")
    out.append("const fe_class_info fe_classes[FE_CLASS_COUNT] = {")
    for c in classes:
        flags = [f.text for f in c.find("flags").findall("flag")] if c.find("flags") is not None else []
        # flag 0 = female class, 3 = promoted, 21 = enemy-only (no playable data)
        out.append("    { %-22s %s, %s, %d, %d, %d },  // %s" % (
            c_str(c.get("name")) + ",",
            c_row(stat_row(c.find("base"))),
            c_row(stat_row(c.find("max"))),
            "0" in flags, "3" in flags, "21" in flags,
            c.get("id")))
    out.append("};")
    out.append("")
    # Support partners per character, in the order of the unit's support block
    out.append("const fe_support_list fe_supports[FE_CHAR_COUNT] = {")
    for u in units:
        sup = u.find("supports")
        pairs = [(int(x.get("unit")), int(x.get("type"))) for x in sup.findall("support")] if sup is not None else []
        body = ", ".join("{%d, %d}" % pt for pt in pairs)
        out.append("    { %2d, { %s } },  // %s" % (len(pairs), body, u.get("name")))
    out.append("};")
    out.append("")
    items = load(os.path.join(DATA, "items.xml"), "item")
    out.append("const fe_item_info fe_items[FE_ITEM_COUNT] = {")
    for it in items:
        st = it.find("stats")
        uses = int(st.get("uses", "0")) if st is not None else 0
        out.append("    { %-26s %2d, %3d },  // %s" % (c_str(it.get("name")) + ",", int(it.get("type1", "10")), uses, it.get("id")))
    out.append("};")
    out.append("")
    # Hero looks (SpotPass/DLC logbook units): ready-made Avatar appearance presets
    heroes = ET.parse(os.path.join(DATA, "einherjar.xml")).getroot().findall("unit")
    out.append("const fe_look_preset fe_look_presets[FE_LOOK_PRESET_COUNT] = {")
    for h in heroes:
        b = h.find("build").attrib
        col = (h.get("color") or "#ffffff").lstrip("#")[:6]
        name = h.get("name").replace(" (DLC)", "")
        hero_head = int(b["face"]) > 4
        out.append("    { %-20s %d, %d, %3d, %d, %d, 0x%s, %d, %3d }," % (
            c_str(name) + ",", int(b["gender"]), int(b["build"]), int(b["face"]), int(b["hair"]),
            int(b["voice"]), col.upper(), 1 if hero_head else 0, int(h.get("logId"))))
    out.append("};")
    out.append("")
    # The same heroes as units (Import an Avatar -> hero list), in preset order
    out.append("const fe_hero_unit fe_hero_units[FE_LOOK_PRESET_COUNT] = {")
    for h in heroes:
        b = h.find("build").attrib
        it = h.find("items").attrib
        g = h.find("growth").attrib
        w = h.find("weapon").attrib
        sk = h.find("skills").attrib
        items_ = [int(it.get("item%d" % i, "0") or 0) for i in range(1, 6)]
        gains = [int(g.get(k, "0") or 0) & 0xFF for k in ("hp", "str", "mag", "skl", "spd", "lck", "def", "res")]
        wexp = [int(w.get(k, "0") or 0) for k in ("sword", "lance", "axe", "bow", "tome", "staff")]
        skl = [int(sk.get("skill%d" % i, "0") or 0) for i in range(1, 6)]
        out.append("    { %3d, %2d, %2d, %d, %d, {%s}, {%s}, {%s}, {%s} },  // %s" % (
            int(b["class"]), int(h.get("level", "1")), int(h.get("unit", "2")), int(b["asset"]), int(b["flaw"]),
            ", ".join(map(str, items_)), ", ".join(map(str, gains)), ", ".join(map(str, wexp)),
            ", ".join(map(str, skl)), h.get("name")))
    out.append("};")
    out.append("")
    out.append("const fe_skill_info fe_skills[FE_SKILL_COUNT] = {")
    for i in range(len(skills)):
        e = skills[i]
        out.append("    { %-24s %d },  // %d" % (c_str(e.get("name")) + ",", 1 if e.get("dlcItem") == "true" else 0, i))
    out.append("};")
    out.append("")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(out))

    print("wrote %s: %d characters, %d classes, %d hero looks" % (OUT, len(units), len(classes), len(heroes)))
    print("check include/core/fedata.h: FE_CHAR_COUNT=%d FE_CLASS_COUNT=%d FE_SKILL_COUNT=%d"
          % (len(units), len(classes), len(skills)))


if __name__ == "__main__":
    main()
